name: Build and Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          meson ninja-build cmake pandoc

    - name: Cache Tcl 9.0.3 build
      id: cache-tcl9
      uses: actions/cache@v5
      with:
        path: /opt/tcl9
        key: ${{ runner.os }}-tcl-9.0.3

    - name: Build Tcl 9.0.3
      if: steps.cache-tcl9.outputs.cache-hit != 'true'
      run: |
        sudo mkdir -p /opt/tcl9
        sudo chown -R $(id -u) /opt/tcl9
        mkdir -p /tmp/src/tcl
        cd /tmp/src/tcl
        wget https://core.tcl-lang.org/tcl/tarball/core-9-0-3/tcl.tar.gz -O - | tar xz --strip-components=1
        cd unix
        ./configure --prefix=/opt/tcl9
        make -j $(nproc)
        make install

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build and test (meson)
      env:
        PKG_CONFIG_PATH: /opt/tcl9/lib/pkgconfig
      run: |
        meson setup build-meson
        meson compile -C build-meson
        meson test -C build-meson --print-errorlogs

    - name: Generate dist tarball
      run: meson dist -C build-meson --no-tests --formats=gztar

    - name: Upload tarball
      uses: actions/upload-artifact@v7
      with:
        name: release-tarball
        path: build-meson/meson-dist/s2n-*.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        files: build-meson/meson-dist/s2n-*.tar.gz
